server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  aop:
    proxy-target-class: true
  mail:
    username: 799816968@qq.com
    password: snvtcuqkxnplbffh
    host: smtp.qq.com
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: 799816968@qq.com #可以任意
    properties.mail.display.sendname: 个人信息托管平台 #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pisp?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: root
    # 连接超时时间
    timeout: 0
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 1000
        # 连接池中的最小空闲连接
        min-idle: 100
      cluster:
        refresh:
          adaptive: true
          #20秒自动刷新一次
          period: 20
mybatis-plus:
  #开启驼峰命名法
  configuration:
    #map-underscore-to-camel-case: true
    # xml地址
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
    # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:   zzu.mmy.pisp.entity
  #自己的实体类地址
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
file:
  uploadPath: D:/PISPFile/
  temp: D:/PISPFile/temp/
rsa:
  publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDFhxWzzZsrvcUvhx0K/0hlp9FgbDUHy+Jo6EkdTU8zmm+1luaKZa+mVbTn9ywNu+gI9eaQjfjmoIuQ+SrzShmDEyLV8x69jUTttJcnyQ2KRum/ONTomOcOkXejbs0GA3vIe6D4MC3726NR4fdE0P0eSuHNoHk37k1r6H//OFdmRwIDAQAB
  privateKey: MIICeQIBADANBgkqhkiG9w0BAQEFAASCAmMwggJfAgEAAoGBAMWHFbPNmyu9xS+HHQr/SGWn0WBsNQfL4mjoSR1NTzOab7WW5oplr6ZVtOf3LA276Aj15pCN+Oagi5D5KvNKGYMTItXzHr2NRO20lyfJDYpG6b841OiY5w6Rd6NuzQYDe8h7oPgwLfvbo1Hh90TQ/R5K4c2geTfuTWvof/84V2ZHAgMBAAECgYEAmZPlGM50pja/OKvZtfI0TO2FCm43cR9houVv63tvaBTcZBi2mMZlInOi23Q/aVI/H7BpGt13t4D94rMIZO6pE/LpNuyWd5/9NWGAtW48SuV4HMxVyQxTlS1A09j69InNJOAvlb6FXKmp1cp442OfOEIBP2JfxO9P3o1cz6EDShkCQQD/aCSTCIxqS6cFTj9NoD+jEu0XSG98CfJdVxyMTdK/coJTSNEtEVT60T9a41raHJATpMFRoI4FmzCFNVZIokiVAkEAxfyHWvHz1Lrrvvl0CQLEIzf4J+BG9lN+f/MqEQpjggEckmtsyl/5HJBheVBDbg824wNOCM4v4S+u1tKZtuLQawJBALwrYibhuXHm4trJ12G9mqTuoLbyqxBb07BpKaNFAuwB1Xq+vz3Q8ycHWwH/V0QynwOZ8sPM4lXHDGxX64X/6jECQQCLMewH6KvBGFm+Pqtx2lwDVspFXs0FSdZaJp+gs2kacaWg2530+lyt1GRzYhbGPjQcjqpCTpQjAd8ucYpYpkZZAkEAkWhiXtab2Dv+BYW+cth8EMP4dE5ow4op4KfqH+dHuxXg5EOh1sKobxqoAChq4PMLg0ZoZupDz5d5dHWDdCjkIw==
aes:
  key: 0123456789ABHAEQ
